# Generated by Django 5.2.1 on 2026-09-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEmitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='número do documento')),
                ('tipo_documento', models.CharField(choices=[('voucher', 'Voucher'), ('recibo', 'Recibo')], default='voucher', max_length=10)),
                ('favorecido', models.CharField(blank=True, max_length=20, verbose_name='código do favorecido, sem zeros à esquerda')),
                ('favorecido_nome', models.CharField(blank=True, max_length=150)),
                ('empresa_pagadora_nome', models.CharField(blank=True, max_length=150)),
                ('empresa_pagadora_cnpj', models.CharField(blank=True, max_length=20)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_retencoes', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('emitido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voucher emitido',
                'verbose_name_plural': 'vouchers emitidos',
                'ordering': ('-emitido_em',),
            },
        ),
        migrations.CreateModel(
            name='VoucherEmitidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura', models.CharField(max_length=20)),
                ('tipo_fat', models.CharField(blank=True, max_length=5)),
                ('favor', models.CharField(blank=True, max_length=20, verbose_name='favorecido sem zeros à esquerda')),
                ('tipo', models.CharField(blank=True, max_length=20, verbose_name='COMISSAO.TIPO (BENEFICIO, CONDOCORP, PEAGA)')),
                ('parcela', models.CharField(blank=True, max_length=10, verbose_name='parcela do boleto, como o PDF imprime')),
                ('parcela_comissao', models.CharField(blank=True, max_length=10, verbose_name='COM.parcela, chave do carimbo no Firebird')),
                ('documento', models.CharField(blank=True, max_length=20, verbose_name='número do boleto')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fedhub.voucheremitido')),
            ],
            options={
                'verbose_name': 'item do voucher',
                'verbose_name_plural': 'itens do voucher',
                'indexes': [models.Index(fields=['fatura', 'documento'], name='voucher_item_fatura_doc')],
                'constraints': [models.UniqueConstraint(fields=('voucher', 'fatura', 'favor', 'tipo', 'parcela', 'documento'), name='voucher_item_unico')],
            },
        ),
    ]
