# Generated by Django 5.2.1 on 2026-09-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedhub', '0001_voucher_emitido'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucheremitido',
            name='reconstituido',
            field=models.BooleanField(default=False, verbose_name='registro inferido das parcelas baixadas, não gravado na emissão'),
        ),
    ]
