# Generated by Django 5.2.1 on 2025-09-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
