# Generated by Django 5.2.1 on 2025-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista'), ('ti', 'TI')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
