# Generated by Django 6.0.2 on 2026-04-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, help_text='Data da última vez que a senha foi redefinida', null=True, verbose_name='última redefinição de senha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_count',
            field=models.IntegerField(default=0, help_text='Número de vezes que a senha foi redefinida', verbose_name='contador de redefinições'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token',
            field=models.CharField(blank=True, help_text='Token gerado para recuperação de senha', max_length=255, null=True, verbose_name='token de recuperação'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token_created_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o token de recuperação foi gerado', null=True, verbose_name='data de criação do token'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='reset_password_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o token de recuperação expira', null=True, verbose_name='data de expiração do token'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista'), ('ti', 'TI'), ('faturamento', 'Faturista')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
