# Generated by Django 6.0.2 on 2026-07-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista'), ('ti', 'TI'), ('faturamento', 'Faturista'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
