# Generated by Django 5.2.1 on 2026-09-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usuario_nivel_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista'), ('ti', 'TI'), ('faturamento', 'Faturista'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('condomed', 'Condomed'), ('esocial', 'Condomed eSocial')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
