# Generated by Django 6.0.2 on 2026-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_nivel_esocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuário Comum'), ('comercial', 'Comercial'), ('moderador', 'Moderador'), ('recepcionista', 'Recepcionista'), ('ti', 'TI'), ('faturamento', 'Faturista'), ('faturamento-analista', 'Faturista Analista'), ('financeiro', 'Financeiro'), ('vistoria', 'Vistoria'), ('condomed', 'Condomed'), ('esocial', 'Condomed eSocial')], default='usuario', max_length=20, verbose_name='nível de acesso'),
        ),
    ]
