# Generated by Django 6.0.2 on 2026-09-22 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('snapshot', 'Snapshot (arquivo)'), ('lake', 'Lake')], default='snapshot', max_length=10)),
                ('arquivo', models.CharField(blank=True, max_length=255, verbose_name='caminho ou identificação da fonte')),
                ('gerado_em', models.CharField(blank=True, max_length=30, verbose_name='`gerado_em` do snapshot, como veio')),
                ('extraido_em', models.DateField(blank=True, null=True, verbose_name='data da extração na CORP')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('erro', models.TextField(blank=True)),
                ('contagens', models.JSONField(blank=True, default=dict)),
                ('rejeitos', models.JSONField(blank=True, default=dict)),
                ('duracao_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'carga da CORP',
                'verbose_name_plural': 'cargas da CORP',
                'ordering': ('-iniciada_em',),
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20)),
                ('pessoa', models.CharField(blank=True, max_length=1, verbose_name='F física / J jurídica')),
                ('nome', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'cliente CORP',
                'verbose_name_plural': 'clientes CORP',
            },
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('nosnum', models.IntegerField(primary_key=True, serialize=False)),
                ('codfil', models.IntegerField(blank=True, null=True, verbose_name='filial — ausente no snapshot (PA-020)')),
                ('tipdoc', models.CharField(max_length=2, verbose_name='A apólice; X, C, R, I, M, F sem legenda (PA-020)')),
                ('cliente_nome', models.CharField(blank=True, max_length=200, verbose_name='nome como veio na produção')),
                ('inivig', models.DateField(blank=True, null=True, verbose_name='início de vigência')),
                ('fimvig', models.DateField(blank=True, null=True, verbose_name='fim de vigência')),
                ('datemi', models.DateField(blank=True, null=True, verbose_name='data de emissão — corte de todos os períodos')),
                ('datemi_bruta', models.CharField(blank=True, max_length=20, verbose_name='texto original quando `datemi` veio inválida')),
                ('nosnum_ren', models.IntegerField(blank=True, null=True, verbose_name='apólice que esta renova (cadeia da CORP)')),
                ('cancelado', models.BooleanField(default=False)),
                ('renovacao_situacao', models.IntegerField(blank=True, null=True, verbose_name='1 vigente, 2 renovada, 3 não renovada, 5 sem legenda, 6 cancelada, -1 sem informação')),
                ('sin_situacao', models.IntegerField(blank=True, null=True, verbose_name='situação de sinistro')),
                ('renovacao', models.BooleanField(default=False)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='indicadores.cargacorp')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='indicadores.cliente')),
            ],
            options={
                'verbose_name': 'produção',
                'verbose_name_plural': 'produções',
            },
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('abreviatura', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'ramo',
                'verbose_name_plural': 'ramos',
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('sigla', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'seguradora',
                'verbose_name_plural': 'seguradoras',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('producao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documento', serialize=False, to='indicadores.producao')),
                ('pretot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='prêmio total')),
                ('val_c', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='comissão')),
                ('preliq', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='prêmio líquido')),
                ('fonte', models.CharField(blank=True, choices=[('D', 'detalhe do documento'), ('R', 'feed de renovações')], max_length=1)),
            ],
            options={
                'verbose_name': 'documento (valores)',
                'verbose_name_plural': 'documentos (valores)',
            },
        ),
        migrations.CreateModel(
            name='DocumentoNegocio',
            fields=[
                ('producao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='documentonegocio', serialize=False, to='indicadores.producao')),
                ('codigo_negocio', models.CharField(blank=True, max_length=30)),
                ('datinc_negocio', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'negócio de origem',
                'verbose_name_plural': 'negócios de origem',
            },
        ),
        migrations.AddField(
            model_name='producao',
            name='ramo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='indicadores.ramo'),
        ),
        migrations.AddField(
            model_name='producao',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producoes', to='indicadores.seguradora'),
        ),
        migrations.AddIndex(
            model_name='producao',
            index=models.Index(fields=['datemi'], name='iex_producao_datemi'),
        ),
        migrations.AddIndex(
            model_name='producao',
            index=models.Index(fields=['fimvig'], name='iex_producao_fimvig'),
        ),
        migrations.AddIndex(
            model_name='producao',
            index=models.Index(fields=['seguradora', 'datemi'], name='iex_producao_seg_datemi'),
        ),
        migrations.AddIndex(
            model_name='producao',
            index=models.Index(fields=['cliente', 'inivig'], name='iex_producao_cli_inivig'),
        ),
        migrations.AddIndex(
            model_name='producao',
            index=models.Index(fields=['nosnum_ren'], name='iex_producao_nosnum_ren'),
        ),
    ]
