# Generated by Django 6.0.2 on 2026-09-23 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_espelho_corp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='mês da meta — sempre dia 1')),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='meta em R$ (valor fechado = soma de pretot)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_criadas', to=settings.AUTH_USER_MODEL)),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='indicadores.ramo')),
                ('seguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='indicadores.seguradora')),
            ],
            options={
                'verbose_name': 'meta mensal',
                'verbose_name_plural': 'metas mensais',
                'ordering': ('competencia', 'seguradora', 'ramo'),
                'indexes': [models.Index(fields=['competencia'], name='iex_meta_competencia')],
                'constraints': [models.UniqueConstraint(fields=('seguradora', 'ramo', 'competencia'), name='iex_meta_seg_ramo_comp')],
            },
        ),
    ]
