# Generated by Django 5.2.1 on 2025-09-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=100)),
                ('participantes', models.TextField()),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=5)),
                ('duracao', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
