# Generated by Django 6.0.2 on 2026-06-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionarioProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=255)),
                ('responsavel_entrevista', models.CharField(max_length=255)),
                ('participantes', models.TextField(blank=True, default='')),
                ('data_entrevista', models.DateField()),
                ('principais_processos', models.TextField(blank=True, default='')),
                ('atividades_frequencia', models.TextField(blank=True, default='')),
                ('informacoes_consultadas', models.TextField(blank=True, default='')),
                ('sistemas_utilizados', models.TextField(blank=True, default='')),
                ('multiplas_fontes', models.TextField(blank=True, default='')),
                ('atividades_manuais_retrabalho', models.TextField(blank=True, default='')),
                ('erros_perda_tempo', models.TextField(blank=True, default='')),
                ('dependencia_outro_setor', models.TextField(blank=True, default='')),
                ('relatorios_indicadores', models.TextField(blank=True, default='')),
                ('melhorias_impacto', models.TextField(blank=True, default='')),
                ('consideracoes_finais', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionarios_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Questionário de Processo',
                'verbose_name_plural': 'Questionários de Processos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
