# Generated by Django 6.0.2 on 2026-06-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionarioprocesso',
            name='subarea',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
