# Generated by Django 5.2.1 on 2025-07-16 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('cpf', 'Consulta de CPF'), ('cnpj', 'Consulta de CNPJ'), ('endereco', 'Consulta de Endereço')], max_length=10)),
                ('parametro_consulta', models.CharField(max_length=100)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('planilha', 'Planilha')], default='manual', max_length=10, verbose_name='origem da consulta')),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.JSONField(blank=True, null=True)),
                ('lote_id', models.UUIDField(blank=True, default=None, help_text='ID único para agrupar consultas de um mesmo upload de planilha.', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_consultas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'histórico de consulta',
                'verbose_name_plural': 'históricos de consultas',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
