# Generated by Django 5.2.1 on 2025-07-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoconsulta',
            name='parametro_consulta',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicoconsulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('cpf', 'Consulta de CPF'), ('cnpj', 'Consulta de CNPJ'), ('endereco', 'Consulta de Endereço'), ('cpf_alternativa', 'Consulta de CPF por Chaves Alternativas')], max_length=20),
        ),
    ]
