# Generated by Django 5.2.1 on 2025-07-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_alter_historicoconsulta_parametro_consulta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoconsulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('cpf', 'Consulta de CPF'), ('cnpj', 'Consulta de CNPJ'), ('endereco', 'Consulta de Endereço'), ('cpf_alternativa', 'Consulta de CPF por Chaves Alternativas'), ('cnpj_razao_social', 'Consulta de CNPJ por Razão Social'), ('cep_rua_cidade', 'Consulta de CEP por Chaves Alternativas'), ('cnpj_comercial', 'Consulta Comercial de CNPJ'), ('comercial', 'Consulta contato Comercial')], max_length=30),
        ),
    ]
