# Generated by Django 5.2.1 on 2025-09-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_historicoconsulta_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoconsulta',
            name='tipo_consulta',
            field=models.CharField(choices=[('cpf', 'Consulta de CPF'), ('cnpj', 'Consulta de CNPJ'), ('endereco', 'Consulta de Endereço'), ('cpf_alternativa', 'Consulta de CPF por Chaves Alternativas'), ('cnpj_razao_social', 'Consulta de CNPJ por Razão Social'), ('cep_rua_cidade', 'Consulta de CEP por Chaves Alternativas'), ('cnpj_comercial', 'Consulta Comercial de CNPJ'), ('comercial', 'Consulta contato Comercial'), ('vida', 'Consulta de segurados Vida'), ('incendio', 'Consulta de segurados Incendio'), ('faturas', 'Consulta de faturas')], max_length=30),
        ),
    ]
