# Generated by Django 5.2.1 on 2025-09-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_comercial', '0002_agendamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
