# Generated by Django 5.2.1 on 2025-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_comercial', '0003_agendamento_hora_agendamento_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
