# Generated by Django 5.2.1 on 2025-10-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoIncendio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incendio_conteudo', models.FloatField(verbose_name='Incêndio Conteúdo')),
                ('perda_aluguel', models.FloatField(verbose_name='Perda de Aluguel')),
                ('repasse_percentual', models.FloatField(verbose_name='Repasse Percentual')),
                ('premio_proposto', models.FloatField(verbose_name='Prêmio Proposto')),
                ('is_total', models.FloatField(verbose_name='IS Total')),
                ('premio_liquido', models.FloatField(verbose_name='Prêmio Líquido')),
                ('repasse', models.FloatField(verbose_name='Repasse (Taxa)')),
                ('comissao_administradora', models.FloatField(verbose_name='Comissão da Administradora')),
                ('assistencia_basica', models.FloatField(verbose_name='Assistência Básica')),
                ('taxa_seguradora', models.FloatField(verbose_name='Taxa da Seguradora')),
                ('premio_liquido_seguradora', models.FloatField(verbose_name='Prêmio Líquido da Seguradora')),
                ('premio_bruto_seguradora', models.FloatField(verbose_name='Prêmio Bruto da Seguradora')),
                ('repasse_seguradora_bruto', models.FloatField(verbose_name='Repasse Seguradora Bruto')),
                ('imposto', models.FloatField(verbose_name='Imposto')),
                ('repasse_liquido', models.FloatField(verbose_name='Repasse Líquido')),
                ('entradas', models.FloatField(verbose_name='Entradas')),
                ('saidas', models.FloatField(verbose_name='Saídas')),
                ('resultado', models.FloatField(verbose_name='Resultado Final')),
                ('percentual', models.FloatField(verbose_name='Percentual do Resultado')),
                ('data_cotacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Cotação')),
            ],
            options={
                'verbose_name': 'Cotação de Incêndio',
                'verbose_name_plural': 'Cotações de Incêndio',
                'ordering': ['-data_cotacao'],
            },
        ),
    ]
