# Generated by Django 5.2.1 on 2026-08-31 19:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmaCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(choices=[('AUDITORIO', 'Auditório'), ('SALA_REUNIAO', 'Sala de reunião')], max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.time(9, 0))),
                ('hora_fim', models.TimeField(default=datetime.time(17, 30))),
                ('administradora_codigo', models.CharField(max_length=20)),
                ('administradora_nome', models.CharField(blank=True, max_length=150)),
                ('condominio_nome', models.CharField(max_length=150)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas_cipa_criadas', to=settings.AUTH_USER_MODEL)),
                ('reserva_sala', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turma_cipa', to='agenda.reserva')),
            ],
            options={
                'verbose_name': 'turma CIPA',
                'verbose_name_plural': 'turmas CIPA',
                'ordering': ['data', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11)),
                ('funcao', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='condomed.turmacipa')),
            ],
            options={
                'verbose_name': 'inscrição CIPA',
                'verbose_name_plural': 'inscrições CIPA',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='turmacipa',
            index=models.Index(fields=['local', 'data'], name='condomed_local_data_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscricaocipa',
            unique_together={('turma', 'cpf')},
        ),
    ]
