# Generated by Django 5.2.1 on 2026-09-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condomed', '0003_cnpj_do_condominio_e_instrutor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaocipa',
            name='presenca',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaocipa',
            name='presenca_registrada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscricaocipa',
            name='presenca_registrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_cipa_registradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
