# Generated by Django 5.2.1 on 2026-09-08 20:52

import django.db.models.deletion
from django.db import migrations, models


def semear_locais_e_instrutores(apps, schema_editor):
    """Os dois locais e os dois instrutores fixos viram registros; toda turma aponta para eles.

    Semente em `condomed.models.LOCAIS_CIPA` / `INSTRUTORES_CIPA` (mantidos só
    para isto). A assinatura sai de `condomed/assets/` para o storage padrão
    (S3 em produção). Idempotente: roda de novo sem duplicar.
    """
    from django.core.files import File

    from condomed.models import ASSETS, INSTRUTORES_CIPA, LOCAIS_CIPA, SALA_REUNIAO

    Local = apps.get_model("condomed", "LocalCipa")
    Instrutor = apps.get_model("condomed", "InstrutorCipa")
    Turma = apps.get_model("condomed", "TurmaCipa")

    for codigo, dados in LOCAIS_CIPA.items():
        Local.objects.get_or_create(
            codigo=codigo,
            defaults={
                "nome": dados["nome"],
                "predio": dados["predio"],
                "capacidade": dados["capacidade"],
                "unidade": "RIO",
                "compartilha_sala_reuniao": codigo == SALA_REUNIAO,
            },
        )
    for codigo, dados in INSTRUTORES_CIPA.items():
        instrutor, _ = Instrutor.objects.get_or_create(
            codigo=codigo,
            defaults={
                "nome": dados["nome"],
                "titulo": dados["titulo"],
                "registro_mte": dados["registro_mte"],
                "registro_uf": dados["registro_uf"],
            },
        )
        asset = ASSETS / dados["assinatura"]
        if not instrutor.assinatura and asset.exists():
            with asset.open("rb") as arquivo:
                instrutor.assinatura.save(dados["assinatura"], File(arquivo), save=True)

    locais = {l.codigo: l.id for l in Local.objects.all()}
    instrutores = {i.codigo: i.id for i in Instrutor.objects.all()}
    for turma in Turma.objects.all():
        turma.local_ref_id = locais[turma.local]
        turma.instrutor_ref_id = instrutores.get(turma.instrutor) if turma.instrutor else None
        turma.save(update_fields=["local_ref", "instrutor_ref"])


def desfazer_semente(apps, schema_editor):
    Turma = apps.get_model("condomed", "TurmaCipa")
    for turma in Turma.objects.select_related("local_ref", "instrutor_ref"):
        turma.local = turma.local_ref.codigo if turma.local_ref else turma.local
        turma.instrutor = turma.instrutor_ref.codigo if turma.instrutor_ref else ""
        turma.save(update_fields=["local", "instrutor"])


class Migration(migrations.Migration):

    dependencies = [
        ('condomed', '0004_presenca_por_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=80)),
                ('predio', models.CharField(blank=True, max_length=120)),
                ('capacidade', models.PositiveIntegerField()),
                ('unidade', models.CharField(choices=[('RIO', 'CondoMed Rio')], default='RIO', max_length=10)),
                ('compartilha_sala_reuniao', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'local CIPA',
                'verbose_name_plural': 'locais CIPA',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='turmacipa',
            name='instrutor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='turmacipa',
            name='local',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='InstrutorCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('titulo', models.CharField(default='Técnico em Segurança no Trabalho', max_length=100)),
                ('registro_mte', models.CharField(max_length=20)),
                ('registro_uf', models.CharField(max_length=2)),
                ('assinatura', models.ImageField(blank=True, upload_to='condomed/assinaturas/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'instrutor CIPA',
                'verbose_name_plural': 'instrutores CIPA',
                'ordering': ['nome'],
                'unique_together': {('registro_mte', 'registro_uf')},
            },
        ),
        migrations.AddField(
            model_name='turmacipa',
            name='instrutor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='condomed.instrutorcipa'),
        ),
        migrations.AddField(
            model_name='turmacipa',
            name='local_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='condomed.localcipa'),
        ),
        migrations.RunPython(semear_locais_e_instrutores, desfazer_semente),
    ]
