# Generated by Django 5.2.1 on 2026-09-09 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condomed', '0006_turma_aponta_para_cadastros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(unique=True)),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoCipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('codigo_verificacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('emitido_em', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_cipa_emitidos', to=settings.AUTH_USER_MODEL)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificado', to='condomed.inscricaocipa')),
            ],
            options={
                'verbose_name': 'certificado CIPA',
                'verbose_name_plural': 'certificados CIPA',
                'ordering': ['numero'],
            },
        ),
    ]
